MacPython/scipy-wheels

README.rst
=> DOC: add a note not to push the SciPy release tag until all wheel builds are OK

.gitmodules
The necessary distutils changes were merged to master, so we can get
them there.
=> MAINT: obtain numpy-distutils from numpy main repository

.travis.yml, appveyor.yml
Pin build dependencies to "known good" versions.
The argument for pinning build dependencies in this repository is:
The point is to be able to build wheels in a controlled way that we
can be sure works, such that e.g. Cython bugs don't torpedo 
the release process.
Testing whether there are incompatibilities in build dependencies (e.g.
whether latest Cython version works) on the other hand should be done
in the main CI repository.
@rgommers: ping --- I think it would be best to pin the deps also in the daily branch. This way, there is a continuous testing that the process that's going to be used for the releases produces usable wheels.
=> MAINT: pin versions of all build dependencies

LICENSE_win32.txt, appveyor.yml
There's some weird crap in the MSVC 2008 license that requires distributing all of the runtime DLLs at once.
=> Bundle all msvc*90 files because the license requires it

.travis.yml, appveyor.yml, config.sh, run_scipy_tests.py
We don't want to fail wheel builds because of e.g. emitted deprecationwarnings, so make pytest treat warnings only as warnings (which is the default when running scipy.test outside of the development tree).
This probably needs to merged also to master, since we probably don't want to e.g. using matplotlib deprecated behavior at this release stage.
=> Do not fail tests on emitted warnings + use runtests for test running on travis

config.sh
Bash function no longer builds 32-bit wheels on OS X, but the comment indicated otherwise.
=> Update comment in `build_osx_wheel`.

config.sh
=> Update multibuild to the version that supports stripping wheels

config.sh
Numpy distutils appears to only look at the LDFLAGS environment variable
when determining how to link fortran.
Note that distutils and numpy.distutils interpret the LDFLAGS variable
in slightly different ways, with the latter requiring that -shared is
included there. <s>To work around this, we concatenate the Python and numpy
defaults.</s>
[Appveyor build cancelled manually, since this does not touch appveyor config.]
Fixes: #30
=> Set LDFLAGS for stripping at link time

appveyor.yml
We had 'wheel==0.26' pinned to avoid problems with old pip versions that
had issues with platform tags.  Today this is no longer any problem, so
unpin the wheel package version.
=> Unpin 'wheel' package version

appveyor.yml
=> Set NUMPY_TEST_DEP according to wheel availability for Windows py3.7 builds

.travis.yml, appveyor.yml
As [discussed](https://github.com/scipy/scipy/issues/9464#issuecomment-437541036) with @rgommers and @charris, bumping Cython version in preparation for  SciPy `1.2.0rc1` wheel building.
I've not messed with the Cython `language_level` directive stuff that now emits a FutureWarning -- leaving that alone seemed ok for generating the source distributions, though I don't know if that's bad practice.
Not sure if I'm going to need elevated permissions for this repo or not -- I think I'll need to create a branch for 1.2.x for wheel building soon, right? And point the wheel builds to the appropriate 1.2.x scipy repo branch rc commit.
=> MAINT: bump Cython to 0.29.0

.travis.yml, appveyor.yml
- Do not build wheels for Python 2.7 and Python 3.4
- Increase NumPy minimum version to 1.13.3.
=> Remove Python 2.7 and Python 3.4 from master builds.

appveyor.yml, env_vars.sh
Update to the fixed up v0.3.4 version, which is sadly named as being
v0.3.3. The newer library fixes many threading problems found in the
earlier version as well as other bugs, in particular https://github.com/scipy/scipy/issues/9620.
Note that this PR also upgrades the OS X deployment target from 10.6 to
10.9, which is needed because the new OpenBLAS libraries target that
version.
=> Update SciPy v1.2.x to OpenBLAS 3.4+

.travis.yml, appveyor.yml
Our master branch scipy wheels Travis cron jobs are failing because the pin to Cython `0.29.0` no longer meets our minimum requirement. For those jobs that are pinned to the minimum version, this PR should bump to the one we now require.
We don't have Appveyor cron jobs as far as I can tell, but there's a similar setting there that I've changed in the same way.
=> MAINT: bump min Cython version

appveyor.yml, env_vars.sh
* bump the version of OpenBLAS used
in SciPy wheel builds to match upstream
fixes for AVX kernel handling on SkylakeX
architecture (basically, they get turned off)
For more details, see the SciPy Intel SDE SkylakeX emulation CI run: https://github.com/scipy/scipy/pull/10145
I may have to seriously consider cherry-picking this to the 1.3.x wheels branch. Perhaps I can delay 1.2.x  LTS OpenBLAS bump for the time being though.
=> MAINT: bump OpenBLAS to 0.3.7.dev

.travis.yml, appveyor.yml
Due to the addition of pocketfft to scipy, pybind11 is now a build dependency.
=> MAINT: add pybind11 build dependency

appveyor.yml
Noticed this based on code highlighted by Pauli here: https://github.com/scipy/scipy/issues/10628
A follow-up PR may be needed if a decision is reached on the Python 3.7+ issue described there.
* remove some comments and code related
to versions of Python we no longer support;
the LTS Python 2.7 branch has its own wheels
branch that won't be affected by this
I suspect even more cleanup is possible depending on the 3.5 support timeline, but perhaps this is a conservative start.
=> MAINT: remove some old Python content

appveyor.yml, env_vars.sh
* use OpenBLAS `v0.3.7` stable release to build scipy
wheels instead of a commit on the development branch
prior to this release
=> MAINT: bump to OpenBLAS 0.3.7 stable

config.sh
The build fails when trying to install pytest-forked included via
TEST_DEPENDS, when it tries to easy-install via setup_requires the
setuptools_scm package, encountering some TLS download errors.  Work
around this by pre-installing the package via pip.
=> Fix py35-osx build on travis

appveyor.yml
All Python versions need the C++ CRT msvcp140.dll since it is not
shipped together with Python.org Python binary.
In principle, the use can download and install the MSVCRT runtime from
Microsoft (and often it is already installed as a part of some other program),
but there are cases where the library is not present already which leads to
the generic "DLL load failed" error message which is hard to debug.
In appveyor.yml the copying was done separately for different Python versions,
because it used to be the case that they used different versions of MSVC.
However, the current versions all use MSVC 14.0.
Closes: https://github.com/scipy/scipy/issues/10628
=> MAINT: bundle msvcp140.dll always

.travis.yml, appveyor.yml
* four of the master branch SciPy wheels
Travis CI matrix entries are erroring with
a message: "Building SciPy requires Cython >= 0.29.13, found 0.29.2"
* so, bumping Cython to 0.29.13 in an attempt to
fix this error
Note that I'd still expect those jobs to fail, but SciPy should at least build if this helps. There appears to be another issue even if Cython is updated.
=> MAINT: bump Cython for Travis wheels

appveyor.yml, check_installed_package.py, check_license.py, config.sh
The fixes from #58 are needed for the `1.3.x` wheels branch as well.
=> DLL handling fixes for 1.3.x

appveyor.yml
* upstream work in openblas-libs accidentally
regenerated at least a few of the zip files
we use from rackspace for OpenBLAS v0.3.7 in wheel
build workflows; adjust the sha256 in those
cases where failures were recently observed
due to mismatches
Reference log with only 32-bit Windows sha256 mismatches: https://ci.appveyor.com/project/scipy/scipy-wheels/builds/29611388
=> MAINT: update OpenBLAS sha256

.travis.yml
* Linux & Mac Python 3.5 matrix entries have
been removed from Travis---this version
of Python is no longer supported by our
master branch of SciPy
* Linux and Mac Python 3.6 Travis CI jobs
were failing because CYTHON_BUILD_DEP
was pinned to version 0.29.13; bump
to required minimum 0.29.14
The other failure in the Travis CI cron job results is more difficult to solve (source code issue I think).
I haven't touched Appveyor yet. There will need to be some more updates of course, but this is hopefully a decent start.
=> MAINT: several wheels repo updates

appveyor.yml
* scipy-wheels master branch Appveyor builds
are failing for Python 3.6 because Cython is
pinned to 0.29.13; this PR bumps to the required
0.29.14
* SciPy master branch no longer supports Python 3.5,
so remove these two builds from the Appveyor
matrix
=> MAINT: Windows/Appveyor updates

.travis.yml
* MacOS Python 3.7 wheel builds were
recently pinned to an older version
of multibuild in the main & wheels repos
for SciPy
* it was possible to build successfully
in main repo after unpinning multibuild
for the same Mac OS Python version
in: https://github.com/scipy/scipy/pull/11419
* so, unpin multibuild for MacOS Python 3.7
in the wheels repo to enable pip20 support,
etc.
One or two minor adjustments may be needed to get this working
just right --- a spurious version of gcc had to be removed
in https://github.com/scipy/scipy/pull/11419 for example
=> MAINT: unpin MacOS PY37 multibuild

.travis.yml
Supersedes #68 because testing the secret API key for anaconda.org uploads likely requires that the feature branch originates in the repo itself.
Don't merge yet---still in a debug state with matrix largely commented out.
=> Anaconda org weekly upload

appveyor.yml
* switch to using `anaconda.org` for OpenBLAS downloads
in our Windows wheel build infrastructure to avoid future
charges from Rackspace to OSS community
* this involves offloading most of the download logic
to `tools/openblas_support.py`
@mattip @pv @rgommers Any security concerns with removal of the hash checking here? Does that need to be added to `openblas_support.py` in the main repo?
=> MAINT: appveyor rack->conda.org

.gitignore, .travis.yml
* for merges (pushes) into `master` and other feature
branches (i.e., release branches), add Travis CI code
to upload to `multibuild-wheels-staging` area, which
would be used for staging before releases, etc.
* update `.gitignore` with standard vim tags from
`github/gitignore` repo, so I don't have to look
at swap files in my staging area
@mattip @ogrisel @rgommers 
Note that the  `multibuild-wheels-staging` storage is already looking close to full, and SciPy hasn't even started using this resource:
=> MAINT: add Travis staging uploads

.travis.yml
* Travis wheel uploads, both for weekly and merge
events, are failing with an apparent syntax issue:
* push event log example fail:
https://travis-ci.org/github/MacPython/scipy-wheels/jobs/686382191
* cron event log example fail:
https://travis-ci.org/github/MacPython/scipy-wheels/jobs/686383899
* looks like a `;` is missing at the end of some `pip install` lines
in conditional blocks, so add those in to prevent the `pip install`
command from propagating to the next line
=> MAINT: Travis upload syntax

appveyor.yml
* turn on conda.org uploads for appveyor CI;
we never did weekly uploads for Appveyor/Windows
wheels so just turn on for merge events
* hopefully this will restrict to merges and not
successful PR branch runs by virtue of secret variable
availability only within the repo itself (so most PRs
should be opened from forks where possible)
=> MAINT: appveyor conda.org uploads

config.sh, env_vars.sh
Fixes #72 
* Appveyor CI wheel builds already use `openblas_support.py`; use the
same script for `OpenBLAS` dependency handling in Travis CI for
wheel builds
* this approach is based on the one described by @mattip for
NumPy wheels in the cognate issue, except that for SciPy we should
not need `urllib3` because of our different approaches to file
downloading in `openblas_support.py`
@rgommers @pv Note that this means `OpenBLAS` version bumps have to happen through merges to the maintenance branch via changes to `openblas_support.py` rather than setting an ENV variable in the wheels repo to bump the version.
=> MAINT: use `openblas_support.py` for Travis

.travis.yml, appveyor.yml
* the minimum required Cython version to build
SciPy is now `0.29.18`; this change has been pushed
directly to the `v1.5.x` wheels feature branch because
of observed failures there, so this is effectively
a forward-port of that
=> MAINT: bump Cython to min required

.travis.yml, extra_functions.sh
* as outlined in gh-77, downstream projects will have
a hard time automatically downloading our most recent
"nightly" (actually weekly) wheel uploads if we don't
add a timestamp of sorts
* this patch attempts to "borrow" the machinery added by
Matti in https://github.com/MacPython/numpy-wheels/pull/84
for this purpose
I believe this has already impacted one project for @bashtage
cc @mattip @rgommers 
I don't want this to automatically `close` gh-77 because we should check the next nightly upload filenames once this is ready & merged (weekly uploads happen on Tuesdays, for POSIX platforms only)
=> MAINT: timestamp nightlies

appveyor.yml
We want numpy.distutils to write a `__config__.py` that uses
os.add_dll_directory when available instead of modifying PATH.
This requires Numpy >= 1.18.0 so we need to replace distutils
from the numpy-distutils clone currently for all Python versions.
I overlooked this when merging gh-88
=> MAINT: replace numpy distutils also for Python >= 3.8

appveyor.yml
Our latest Windows Python 3.6 wheel appears to fix the downstream CI DLL load issue in pytorch based on a debug PR leveraging that staged wheel: https://github.com/pytorch/pytorch/pull/40975
So, as part of the process of preparing for `SciPy 1.5.1`, backport the wheels repo fixes involved in that fix:
- #89 
- #88 
cc @pv
=> MAINT: Backport windll fixes 151

.travis.yml, config.sh
fixes [#11170](https://github.com/scipy/scipy/issues/11170)
Added job to build AArch64 wheel
=> Add support to AArch64 wheel

.travis.yml
* expand the Travis CI ARM64 builds to include
Python 3.6 and Python 3.8 (since we need those wheels too), using separate
workspaces to pass data between stages for them
cc @janaknat @mattip @odidev  
Probably won't work on first try, but it looks like we [do have support](https://github.com/scipy/scipy/issues/11170#issuecomment-701674909) to release ARM64 wheels with `1.5.3`
=> MAINT: expand ARM64 builds

.travis.yml
Fixes #96 
* add Travis CI job names as Matti suggested, since the matrix
is getting pretty large
=> MAINT: add Travis CI job names

.travis.yml, appveyor.yml, config.sh
* try adding the ARM64 wheel builds to the `v1.5.x` wheels branch--an early sniff test to see if we run into issues with provision of ARM wheels for Linux on this older release branch
* point the builds to the tip of the maintenance branch in the main repo while I'm at it to get latest build of the branch
* the only notable backport I left out from `master` was a `multibuild` submodule bump; can do that if needed but being conservative initially
=> MAINT: ARM64 & related backports

README.rst
* update the `README` file to reflect our recent migration
to new Travis CI site (`.com` instead of `.org`)
for wheel builds
=> DOC, MAINT: update README Travis CI

appveyor.yml
* try activating Python 3.9 wheel builds
for Windows/Appveyor
=> MAINT: turn on Windows Python 3.9

.travis.yml
* this will almost certainly fail for now,
but draft in changes for Python 3.9 entries
in Travis CI
=> CI: turn on Python 3.9 in Travis CI

.travis.yml, appveyor.yml
* backport gh-98 to add Python 3.9 wheels builds/tests for POSIX systems (Windows already backported) and update the `BUILD_COMMIT` to get an idea of where we stand prior to SciPy `1.5.4` release.
=> MAINT: backport Python 3.9 POSIX additions

azure-posix.yml
Fixes #112
* we already `--force` uploads on Travis
and Appveyor; otherwise, we can't upload
fixed versions of releases to staging areas
on Azure
* use Travis skip tags to avoid wasting travis
resources here
[skip travis] [skip travis-ci]
=> MAINT: force azure uploads

.travis.yml, appveyor.yml, azure-posix.yml
Fixes #115
Forward-port the fix that worked for the `v1.6.x` wheels branch `anaconda-client` upload issue. Does not affect Azure Pipelines because they use `conda` to obtain the dependency instead of `pip`.
* pin the `anaconda-client` commit hash used for
Travis and Appveyor `pip` installs to avoid a
problematic dependency addition to `requirements.txt`
=> MAINT: pin anaconda-client and add pythran build dependency

README.rst
May fix the Pythran issue by treating CFLAGS, LDFLAGS in a more appropriate way.
Also includes a small README update that was overdue.
=> Add README update for Azure CI link

appveyor.yml
This change is copied from the Azure setup in the main SciPy repo. It should fix the Pythran build issue.
=> Add -m32 to the 32-bit Python on Windows builds

appveyor.yml
Fixes #120 
* try to fix absence of boost submodule in Appveyor
wheel builds; note that this is the third usage
of `git submodule update --init` in the Appveyor config
file--the previous two use cases were added years ago
by Matthew Brett and Pauli and appear to be related to
the wheels infrastructure rather than the SciPy checkout
proper (the addition here is after `cd scipy` so hopefully
it works..)
* skip Travis CI builds to save credits..
* if/when this works, the patch should likely be pushed right
into the `v1.7.x` wheels branch with Travis skipped as well
[skip travis] [skip travis ci] [skip travis-ci] [travis skip]
=> MAINT: boost submodule Appveyor

appveyor.yml
This changed in Pythran 0.9.10
Fixes:
```
LINK : warning LNK4044: unrecognized option '/m32'; ignored
Release\scipy/interpolate\_rbfinterp_pythran.cp39-win32.lib -m32" failed with exit status 1112
```
=> Change CFLAGS to CXXFLAGS for passing -m32 to Pythran

.travis.yml, appveyor.yml, azure-pipelines.yml, azure-posix.yml, config.sh
cc @judahrand
Wait for
universal2 support was added in https://github.com/scipy/scipy/pull/14316
=> Fixes for latest commit of scipy and add universal2 wheels

.travis.yml, appveyor.yml, azure-pipelines.yml, azure-posix.yml, config.sh
Build wheels for Python 3.10.
xref https://github.com/scipy/scipy/issues/14567 and #124
=> MAINT: add Python 3.10 wheels

.gitmodules, .travis.yml, appveyor.yml, azure-pipelines.yml, azure-posix.yml, config.sh, run_scipy_tests.py
* try to backport some of the pertinent
changes for Python 3.10 support to the wheels
repo `v1.7.x` branch, which needs to continue
supporting Python 3.7
* perhaps we can do away with some of the manylinux
bumps--not sure on those--things are going to change
a fair bit anyway with a huge bump in OpenBLAS version
as well; perhaps the bumps could be confined to just 3.10
using newer manylinux??
* point `BUILD_COMMIT` at the tip of the target maintenance
branch to get more useful feedback on where we stand
for the 3.10 wheel builds
=> WIP, MAINT: backport 3.10 support

appveyor.yml
Fixes https://github.com/scipy/scipy/issues/14998
=> BUG: Includes msvcp140.dll in python 3.10 build on windows

_distributor_init.py
Addresses at least part of https://github.com/scipy/scipy/issues/15050,
TBD if that closes it or if we need to rebuild OpenBLAS instead later.
For now (and for the 1.7.3 release) this is the safest and quickest
improvement.
=> MAINT: set `OPENBLAS_THREAD_TIMEOUT` on arm64 macOS to avoid performance issues

patch_code.sh
=> BUG: now actually include `_distributor_init.py` in macOS arm64 wheel

azure-pipelines.yml, azure-posix.yml, run_scipy_tests.py
* forward-port multiprocessing addition to `run_scipy_tests.py`, which
was helpful in preventing sporadic Appveyor/Windows test failures on the
`v1.7.x` branch
* forward-port Python `3.10` x86_64 thin wheel support
* add Python 3.8 to 3.10 MacOS arm64 thin wheel builds for
MacOS 12; I'll be fairly surprised if the issues for Python < 3.10
download with this super-new OS version observed in the backport PR
are not observed on `master` (need multibuild change or don't actually
need to bump the version that high to restrict to MacOS 12 only
usage of the wheel?)
=> MAINT: add thin wheels, some fixes

azure-posix.yml
* automatically rename MacOS arm64 thin wheel files to
use version `12_0` instead of `11_0`; the verbose file
move should print out the change for us if successful
=> MAINT: rename MacOS arm64 wheels

azure-posix.yml
backport gh-147
* automatically rename MacOS arm64 thin wheel files to
use version `12_0` instead of `11_0`; the verbose file
move should print out the change for us if successful
=> MAINT: backport MacOS arm64 wheel renmaing

appveyor.yml, azure-posix.yml, patch_code.sh, verify_init.py
* following on from continued problems reported here:
https://github.com/scipy/scipy/issues/15050
* draft in code to check that MacOS wheels get
the same `_distributor_init.py` as the one present
in the wheels repo, rather than the generic nearly-empty
copy actually present in the `1.7.3` release
* we've had two pull requests about this and it slipped through into
a release despite 3 sets of eyes so need to be careful here;
I'd like to see the test script added here failing for MacOS in CI
like it does locally, before attempting a fix
* this is likely still WIP, since relative paths/directories
can be confusing to predict in the wheels/multibuild control
flow, which also flushes in and out of containers I think, etc.
(this probably contributed to the original problem)
* the script did …
=> MAINT, CI: check _distributor_init.py contents

azure-pipelines.yml, azure-posix.yml
=> Fix universal2 wheel name and remove redundant builds

appveyor.yml
Proposed temporary workaround for gh-159 on `v1.8.x` branch
* at least temporarily pin the appveyor
Windows build dependencies that jumped
between 1.8.0rc1 and 1.8.0rc2, likely
causing the latter to fail
* this is not likely something that should
be forward ported; instead, we should likely
start leveraging newer PEP-compliant install
commands on Windows/Appveyor instead
of `python setup.py..`
=> MAINT: pin deps for 1.8.x

appveyor.yml
Related to gh-164
* uploading the XML test suite result data to
the Appveyor service has failed for me six
times in a row now, and I need to get this release
out, so this feature branch attempts to disable the
part of the control flow that uploads the XML
data
* the tests themselves should still run, we just
won't see the pretty metadata in the Appveyor
UI for now on the wheels release branch
* `test_quad_vec_pool` may still fail stochastically
b/c of multiprocessing permissions issues on Windows,
but this I can at least restart the failing jobs for,
while the XML upload has a 0 % success rate on 6 consecutive
tries for all matrix entries
=> MAINT: disable test uploads

.travis.yml, azure-posix.yml
Fixes #168 
I just got burned by this for `1.9.0rc1`. I really need to stop doing backport-only fixes, even when I'm in a rush, except when absolutely necessary.
Anyway, let me confirm that this exact patch fixes the issue on `v1.9.x` before merging here (I pushed back first to prioritize current wheel builds).
=> MAINT: setuptools pin

azure-pipelines.yml
We're switching over to cibuildwheel in the main SciPy repo,
so no need for these jobs anymore. The nightlies will be uploaded
from a weekly scheduled run of `cibuildwheel`.
Appveyor doesn't run cron jobs, and TravisCI cron jobs are not defined
in the yml file but in its web UI, so this is all there is to do here.
[ci skip]
=> Stop cron jobs running on master
